title: Watch F1
description: Guide to watch F1TV from non-support country
theme: just-the-docs

url: https://theerapat-s.github.io/watchf1

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
